id: P010320
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W20565
  title: སྙན་འགྲེལ་ཡང་གསལ་སྣང་མཛོད་ལས་དོན་རྒྱན་སོ་ལྔའི་ཚིག་འགྲེལ་དབྱངས་ཅན་པི་ཝང
  author: ''
  volumes:
    97d0ae0a99bd4bcf90d12bcbc02ad0c3:
      image_group_id: I4889
      title: ''
      volume_number: 1
      total_pages: 305
      base_file: v001.txt
